name: SFTP Deploy

on:
  push:
    branches:
      - master

jobs:
  ftp-deploy:
    name: Upload files to FTP server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show working directory and contents
        run: |
          echo "Current directory: $(pwd)"
          ls -lah

      - name: SFTP Deploy
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          source: |
            index.html
            styles.css
            script.js
            images/
          target: "/home/nathanmoeller/public_html"
          overwrite: true
          debug: true
          strip_components: 0
