name: SFTP Deploy

on:
  push:
    branches:
      - master

jobs:
  ftp-deploy:
    name: Upload files to FTP server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add SSH known hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts

      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Upload files via SFTP with lftp
        env:
          HOST: ${{ secrets.FTP_HOST }}
          USER: ${{ secrets.FTP_USERNAME }}
          PASS: ${{ secrets.FTP_PASSWORD }}
          PORT: '22'
        run: |
          # Using lftp mirror to upload all files except hidden
          lftp -u "$USER","$PASS" -p "$PORT" sftp://$HOST <<EOF
            mirror -R --exclude-glob .git* --exclude-glob .github --exclude-glob .* ./ /home/nathanmoeller/public_html/
            quit
          EOF
